runtime: custom
env: flex

network:
    session_affinity: true
env_variables:
    PROJECT_ID: "selfservicedesk"
    LANGUAGE_CODE: "en-US"
    ENCODING: "AUDIO_ENCODING_LINEAR_16"
    SAMPLE_RATE_HERZ: "16000"
    SINGLE_UTTERANCE: "true"