runtime: custom
env: flex
service: googleio

network:
    session_affinity: true
env_variables:
    PROJECT_ID: "selfservicedesk"
    LANGUAGE_CODE: "en-US"
    ENCODING: "AUDIO_ENCODING_LINEAR_16"
    SAMPLE_RATE_HERZ: "16000"
    SINGLE_UTTERANCE: "false"
    SPEECH_ENCODING: "LINEAR16"
    SSML_GENDER: "MALE"
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 5
    cpu_utilization:
        target_utilization: 0.5